# Generated by Django 4.2.21 on 2026-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_name_email_to_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('standard', 'Стандартна заявка'), ('grant_diti', 'Грант діти')], default='standard', max_length=20, verbose_name='Статус'),
        ),
    ]
