# Generated by Django 4.2.21 on 2026-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_consultationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('standard', 'Стандартна заявка'), ('grant_diti', 'Грант діти'), ('children_learning', 'Дитяча навчання')], default='standard', max_length=20, verbose_name='Статус'),
        ),
    ]
