# Generated by Django 4.2.21 on 2026-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_children_learning_status'),
        ('leads', '0007_make_name_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenLearningRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка дитяча навчання',
                'verbose_name_plural': 'Заявки дитяча навчання',
                'proxy': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'indexes': [],
                'constraints': [],
            },
            bases=('core.consultationrequest',),
        ),
    ]
