# Generated by Django 4.2.21 on 2025-12-16 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефон')),
                ('question_1', models.CharField(max_length=10, verbose_name='Питання 1')),
                ('question_2', models.CharField(max_length=10, verbose_name='Питання 2')),
                ('question_3', models.CharField(max_length=10, verbose_name='Питання 3')),
                ('question_4', models.CharField(max_length=10, verbose_name='Питання 4')),
                ('question_5', models.CharField(max_length=10, verbose_name='Питання 5')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sent_to_bitrix', models.BooleanField(default=False)),
                ('bitrix_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
                'ordering': ['-created_at'],
            },
        ),
    ]
