# Generated by Django 4.2.21 on 2025-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва (UK)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Назва (RU)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (однаковий)')),
                ('description_uk', models.TextField(verbose_name='Опис (UK)')),
                ('description_ru', models.TextField(verbose_name='Опис (RU)')),
                ('content_uk', models.TextField(verbose_name='Контент (UK)')),
                ('content_ru', models.TextField(verbose_name='Контент (RU)')),
                ('meta_title_uk', models.CharField(max_length=60, verbose_name='Meta Title (UK)')),
                ('meta_title_ru', models.CharField(max_length=60, verbose_name='Meta Title (RU)')),
                ('meta_description_uk', models.CharField(max_length=160, verbose_name='Meta Description (UK)')),
                ('meta_description_ru', models.CharField(max_length=160, verbose_name='Meta Description (RU)')),
                ('og_title_uk', models.CharField(blank=True, max_length=100, verbose_name='OG Title (UK)')),
                ('og_title_ru', models.CharField(blank=True, max_length=100, verbose_name='OG Title (RU)')),
                ('og_description_uk', models.CharField(blank=True, max_length=200, verbose_name='OG Description (UK)')),
                ('og_description_ru', models.CharField(blank=True, max_length=200, verbose_name='OG Description (RU)')),
                ('og_image', models.ImageField(blank=True, upload_to='programs/og_images/', verbose_name='OG Image')),
                ('icon', models.ImageField(blank=True, upload_to='programs/icons/', verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Програма',
                'verbose_name_plural': 'Програми',
                'ordering': ['order', 'title_uk'],
                'indexes': [models.Index(fields=['slug'], name='main_progra_slug_2f37ad_idx'), models.Index(fields=['is_active', 'order'], name='main_progra_is_acti_e01372_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('slug_uk', models.SlugField(max_length=200, unique=True, verbose_name='Slug (UK)')),
                ('slug_ru', models.SlugField(max_length=200, unique=True, verbose_name='Slug (RU)')),
                ('content_uk', models.TextField(verbose_name='Контент (UK)')),
                ('content_ru', models.TextField(verbose_name='Контент (RU)')),
                ('meta_description_uk', models.CharField(max_length=160, verbose_name='Meta Description (UK)')),
                ('meta_description_ru', models.CharField(max_length=160, verbose_name='Meta Description (RU)')),
                ('og_title_uk', models.CharField(blank=True, max_length=100, verbose_name='OG Title (UK)')),
                ('og_title_ru', models.CharField(blank=True, max_length=100, verbose_name='OG Title (RU)')),
                ('og_description_uk', models.CharField(blank=True, max_length=200, verbose_name='OG Description (UK)')),
                ('og_description_ru', models.CharField(blank=True, max_length=200, verbose_name='OG Description (RU)')),
                ('og_image', models.ImageField(blank=True, upload_to='blog/og_images/', verbose_name='OG Image')),
                ('author', models.CharField(default='SPEAK UP', max_length=100, verbose_name='Автор')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/images/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug_uk'], name='main_blogpo_slug_uk_be6808_idx'), models.Index(fields=['slug_ru'], name='main_blogpo_slug_ru_0651fb_idx'), models.Index(fields=['-published_at'], name='main_blogpo_publish_63153a_idx')],
            },
        ),
    ]
