# Generated by Django 4.2.21 on 2025-12-21 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_program_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефон')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('sent_to_bitrix', models.BooleanField(default=False, verbose_name='Відправлено в Bitrix')),
                ('bitrix_response', models.JSONField(blank=True, null=True, verbose_name='Відповідь Bitrix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка з рекламного лендингу',
                'verbose_name_plural': 'Заявки з рекламного лендингу',
                'ordering': ['-created_at'],
            },
        ),
    ]
