# Generated by Django 4.2.21 on 2026-02-10 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ сесії')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP адреса')),
                ('user_agent', models.CharField(max_length=512, verbose_name='User Agent')),
                ('referrer', models.CharField(blank=True, default='', max_length=2048, verbose_name='Referrer')),
                ('utm_source', models.CharField(blank=True, default='', max_length=255, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=255, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=255, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, default='', max_length=255, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, default='', max_length=255, verbose_name='UTM Term')),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Перше відвідування')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Остання активність')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Це бот')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], default='desktop', max_length=10, verbose_name='Тип пристрою')),
            ],
            options={
                'verbose_name': 'Сесія відвідувача',
                'verbose_name_plural': 'Сесії відвідувачів',
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['first_seen', 'ip_address'], name='analytics_v_first_s_9d6d36_idx'), models.Index(fields=['is_bot', 'first_seen'], name='analytics_v_is_bot_ad2774_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=2048, verbose_name='URL')),
                ('page_title', models.CharField(blank=True, default='', max_length=512, verbose_name='Заголовок сторінки')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час входу')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Проведено секунд')),
                ('is_exit_page', models.BooleanField(default=False, verbose_name='Вихідна сторінка')),
                ('source', models.CharField(choices=[('js', 'JavaScript'), ('server', 'Server')], default='server', max_length=10, verbose_name='Джерело запису')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Перегляд сторінки',
                'verbose_name_plural': 'Перегляди сторінок',
                'ordering': ['entered_at'],
                'indexes': [models.Index(fields=['session', 'entered_at'], name='analytics_p_session_5aa259_idx'), models.Index(fields=['url', 'entered_at'], name='analytics_p_url_9ad4b3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pageview',
            constraint=models.UniqueConstraint(fields=('session', 'url', 'entered_at'), name='unique_pageview'),
        ),
    ]
