# Generated by Django 4.2.21 on 2026-02-10 17:46

from django.db import migrations


def clear_old_data(apps, schema_editor):
    """Очистити всі старі записи (з дублями та ботами)"""
    VisitorSession = apps.get_model('analytics', 'VisitorSession')
    # CASCADE автоматично видалить пов'язані PageView
    deleted_count, _ = VisitorSession.objects.all().delete()
    print(f'Видалено {deleted_count} старих сесій з дублями та ботами')


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_old_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='pageview',
            name='unique_pageview',
        ),
    ]
